# Site settings
title: "포트폴리오"
email: ksqrt.work@gmail.com
description: >-
  2년년차 백엔드 개발자 강성욱의 포트폴리오입니다.
baseurl: ""
url: "https://kminmax.github.io"
twitter_username:
github_username: kminmax

# SEO 설정
author: "강성욱"
lang: "ko"
keywords: "백엔드 개발자, 포트폴리오, Node.js, AWS, Kubernetes, 강성욱"
og_image: "/images/armin.jpg"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
# Google Analytics
google_analytics: G-XDF7Q9NC93

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Dockerfile
  - docker-compose.yml
  - README.md
